---
# roles/terraform/tasks/main.yml

# ----------------------------------------
# DIRECTORY STRUCTURE
# ----------------------------------------

- name: Create Terraform base directory
  ansible.builtin.file:
    path: /srv/terraform
    state: directory
    mode: '0755'

- name: Create Terraform data directory
  file:
    path: /srv/terraform/data
    state: directory
    mode: '0755'

# ----------------------------------------
# DEPLOY COMPOSE FILE
# ----------------------------------------

- name: Deploy Terraform docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /srv/terraform/docker-compose.yml
    mode: '0644'

# ----------------------------------------
# START STACK
# ----------------------------------------

- name: Start Terraform container
  community.docker.docker_compose_v2:
    project_src: /srv/terraform
    state: present
    pull: always

