$ANSIBLE_VAULT;1.1;AES256
61363863333462376233376132623137393133326561343364616438373636383234363965353866
6438376563323965313265366139656561386364323964300a646465376536646565663264653763
32393135353932363234343138343463633562316237303764613631663233383037626335373732
3036373061636239370a633162373035356335623130303138376161643365373130663839383961
31313438393730343161393532386436653838333334656261313433363632626665663130376535
33626131616231306231383234356233623036616238656430306531363632353364633437356365
34613039363166653462663335356632393866386135383065373265633538306465353565636136
39643133383333616138346132626566656330306464636534646364376432353164616336326331
3962
