primary_domain: "pearsalls.online"

root_domain: "{{ primary_domain }}"
traefik_domain: "traefik.{{ primary_domain }}"
grafana_domain: "grafana.{{ primary_domain }}"
prometheus_domain: "prometheus.{{ primary_domain }}"
loki_domain: "loki.{{ primary_domain }}"
promtail_domain: "promtail.{{ primary_domain }}"
cloudflared_domain: "tunnel.{{ primary_domain }}"
portainer_domain: "portainer.{{ primary_domain }}"
crowdsec_domain: "crowdsec.{{ primary_domain }}"
richweb_domain: "richard.{{ primary_domain }}"
petitsanglais_domain: "petitsanglaisabeziers.fr"
esperancefr_domain: "egliseesperanceagde.fr"
esperanceorg_domain: "egliseesperanceagde.org"
