cloudflare_tunnel_hostname: "{{ cloudflare_tunnel_id }}.cfargotunnel.com"

primary_domain: "pearsalls.fr"

root_domain: "{{ primary_domain }}"
traefik_domain: "traefik.{{ primary_domain }}"
grafana_domain: "grafana.{{ primary_domain }}"
prometheus_domain: "prometheus.{{ primary_domain }}"
loki_domain: "loki.{{ primary_domain }}"
promtail_domain: "promtail.{{ primary_domain }}"
cloudflared_domain: "tunnel.{{ primary_domain }}"
portainer_domain: "portainer.{{ primary_domain }}"
crowdsec_domain: "crowdsec.{{ primary_domain }}"
richweb_domain: "richard.{{ primary_domain }}"
dozzle_domain: "dozzle.{{ primary_domain }}"
petitsanglais_domain: "petitsanglaisabeziers.fr"
esperancefr_domain: "egliseesperanceagde.fr"
esperanceorg_domain: "egliseesperanceagde.org"
bentopdf_domain: "bentopdf.{{ primary_domain }}"
semaphore_domain: "semaphore.{{ primary_domain }}"
hantaweb_domain: "hartkenci-elle.com"
vault_domain: "vault.{{ primary_domain }}"
