$ANSIBLE_VAULT;1.1;AES256
37306564306437663733393366626339633463343933626165646261643164623366613637353634
3631303065396131393766346338383434313962383634340a646161663338626235653535303637
38626435613532343637613961383064633966386261623836376333363263663938633238643166
3666333263366265310a386639646432313735336439303761303539626530663634366130663434
35363730303861306562613036306535303761333237306563326561376231306563343737333165
31336535643835383165623738656337643665646666336230353230613966366566663434386630
39626632356134396630623535373033356262616332336234386263386130643433343934356133
34306161393137653030313030306562623864316331383730636162653534393133616161613630
62633936343861613561656361633830623065396430396565343539613633303437666466343865
32333337633732343135363765303230653334356663613530396264353035643230363565376232
32353966326438666533333438303638333435343633373235383561373731336230346130626337
31343566383834626363633765373932356166633530323264613731346562343530623566636364
6236
