$ANSIBLE_VAULT;1.1;AES256
37386639643663633739643435306135646261643565363662326337646464303165313433343734
6562393162386633356462636233393036396233323736640a383461656563363861653032666339
65613265353536633866653135366566336639386261336163396365373038646664373230666531
6163326665323133360a653633653435313539313435346166356132646262353532323734343764
62373065396563396135313963396134353235646464643932636662303364373566626538326538
38363265336338346534323432313362326235306564653839383663386235626539646664373631
39643362363031336563626332653235393339363436613531646334396535306463653830663931
32656565393933666364396362613534366334613831313565663163306237613663626339326364
3934
