$ANSIBLE_VAULT;1.1;AES256
66663837623832316565616661623837353963633038613339616262373431316638383563633366
3461656163313134323635326235376335393236333336320a386161366130326361346261656338
61396539313835326136636362306631343535623135643564626439633138383361336162323166
6461623862363738360a306339366431626238376639386264346633396538353132303965383666
33323664373636346635396466656531346339313065613365643066616636356634333065343736
3566343761336436323136353636373565656230646662336465
