docker_volumes:
  grafana_data: {}
  prometheus_data: {}
  loki_data: {}
  loki_wal: {}
  mariadb_data: {}
  vaultwarden_data: {}
  crowdsec_data: {}
  traefik_data: {}
  cloudflared_data: {}
  petitsanglais_wp: {}
  petitsanglais_db: {}
  petitsanglais_nginx.conf: {}
  hantaweb_wp: {}
  hantaweb_db: {}
  hantaweb_nginx.conf: {}
  richweb_wp: {}
  richweb_db: {}
  richweb_nginx.conf: {}
  esperancefr_wp: {}
  esperancefr_db: {}
  esperancefr_nginx.conf: {}
  esperanceorg_wp: {}
  esperanceorg_db: {}
  esperanceorg_nginx.conf: {}
