docker_volumes:
  grafana_data: {}
  prometheus_data: {}
  loki_data: {}
  loki_wal: {}
  mariadb_data: {}
  vaultwarden_data: {}
  crowdsec_data: {}
  traefik_data: {}
  cloudflared_data: {}
  petitsanglais_wp: {}
  petitsanglais_db: {}
  petitsanglais_nginx_conf: {}
#  hantaweb_wp: {}
#  hantaweb_db: {}
#  hantaweb_nginx_conf: {}
  richweb_wp: {}
  richweb_db: {}
  richweb_nginx_conf: {}
#  esperancefr_wp: {}
#  esperancefr_db: {}
#  esperancefr_nginx_conf: {}
  esperance_wp: {}
  esperance_db: {}
  esperance_nginx_conf: {}
  terraform_data: {}

