vaultwarden_user: vaultwarden
vaultwarden_group: vaultwarden
vaultwarden_data_dir: /var/lib/vaultwarden
vaultwarden_env_file: /etc/vaultwarden.env
vaultwarden_domain: "{{ vault_domain }}"
vaultwarden_port: 8080
vaultwarden_admin_enabled: false
