- name: Deploy vaultwarden environment config
  template:
    src: vaultwarden.env.j2
    dest: /etc/vaultwarden.env
    owner: vaultwarden
    group: vaultwarden
    mode: '0640'
  notify: restart vaultwarden

- name: Enable and start vaultwarden
  systemd:
    name: vaultwarden
    enabled: true
    state: started
