- name: Deploy vaultwarden environment config
  template:
    src: vaultwarden.env.j2
    dest: "{{ vaultwarden_install_dir }}/.env"
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    mode: '0640'
  notify: restart vaultwarden

- name: Enable and start vaultwarden
  systemd:
    name: vaultwarden
    enabled: true
    state: started
