- name: Create vaultwarden group
  group:
    name: "{{ vaultwarden_group }}"
    system: true

- name: Create vaultwarden user
  user:
    name: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    system: true
    shell: /usr/sbin/nologin
    home: "{{ vaultwarden_data_dir }}"
    create_home: false

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"
    mode: '0750'
  loop:
    - "{{ vaultwarden_data_dir }}"
    - "{{ vaultwarden_install_dir }}"

- name: Download vaultwarden binary
  get_url:
    url: "https://github.com/dani-garcia/vaultwarden/releases/download/{{ vaultwarden_version }}/vaultwarden-{{ vaultwarden_version }}-linux-amd64.tar.gz"
    dest: /tmp/vaultwarden.tar.gz
    mode: '0644'

- name: Extract vaultwarden binary
  unarchive:
    src: /tmp/vaultwarden.tar.gz
    dest: "{{ vaultwarden_install_dir }}"
    remote_src: true
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"

- name: Download web vault
  get_url:
    url: "https://github.com/dani-garcia/bw_web_builds/releases/download/{{ vaultwarden_version }}/bw_web_v{{ vaultwarden_version }}.tar.gz"
    dest: /tmp/bw_web.tar.gz
    mode: '0644'

- name: Extract web vault
  unarchive:
    src: /tmp/bw_web.tar.gz
    dest: "{{ vaultwarden_install_dir }}"
    remote_src: true
    owner: "{{ vaultwarden_user }}"
    group: "{{ vaultwarden_group }}"

- name: Install systemd service
  template:
    src: vaultwarden.service.j2
    dest: /etc/systemd/system/vaultwarden.service
    mode: '0644'
  notify:
    - reload systemd
    - restart vaultwarden
