- name: Remove site directory for clean test
  file:
    path: "/srv/wp/{{ site_name }}"
    state: absent

- name: Remove existing containers for clean test
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ site_name }}_nginx"
    - "{{ site_name }}_php"
    - "{{ site_name }}_db"

- name: Remove DB volume for clean test
  community.docker.docker_volume:
    name: "{{ site_name }}_db"
    state: absent
