---
- name: Create global Docker networks
  community.docker.docker_network:
    name: "{{ item.key }}"
    driver: "{{ item.value.driver }}"
    attachable: "{{ item.value.attachable }}"
    state: present
  loop: "{{ docker_networks | dict2items }}"
