---
# roles/monitoring/handlers/main.yml

- name: restart prometheus
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    services:
      - prometheus
    state: restarted

- name: restart loki
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    services:
      - loki
    state: restarted

- name: restart promtail
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    services:
      - promtail
    state: restarted

- name: restart grafana
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    services:
      - grafana
    state: restarted

