monitoring:
  hosts:
    docker-srv:
      ansible_host: docker-srv
      ansible_user: rich
      ansible_become: true
      ansible_become_method: sudo

docker:
  hosts:
    docker-srv:
      ansible_host: docker-srv
      ansible_user: rich
      ansible_become: true
      ansible_become_method: sudo

terraform:
  hosts:
    docker-srv:
      ansible_host: docker-srv
      ansible_user: root
      ansible_become: false

proxmox:
  hosts:
    proxmox-srv:
      ansible_host: proxmox-srv
      ansible_user: root
      ansible_become: false
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
