monitoring:
  hosts:
    srv2:
      ansible_host: 192.168.1.231
      ansible_user: rich
      ansible_become: true
      ansible_become_method: sudo

docker:
  hosts:
    srv2:
      ansible_host: 192.168.1.231
      ansible_user: rich
      ansible_become: true
      ansible_become_method: sudo
