monitoring:
  hosts:
    docker-srv:
      ansible_host: docker-srv
      ansible_user: rich
      ansible_become: true
      ansible_become_method: sudo

docker:
  hosts:
    docker-srv:
      ansible_host: docker-srv
      ansible_user: rich
      ansible_become: true
      ansible_become_method: sudo

