---
- name: Install Automation packages on docker-srv
  hosts: docker
  become: true
  vars_files: 
    - ../group_vars/all/vault.yml
    - ../group_vars/all/semaphore_vault.yml
    - ../group_vars/all/semaphore_vars.yml
  roles:
    - role: semaphore
    - role: ansible
    - role: terraform
