---
- name: Deploy MinIO
  hosts: docker
  vars_files:
    - ../group_vars/all/vault.yml
    - ../group_vars/all/services.yml
    - ../group_vars/all/volumes.yml
  roles:
    - docker-volumes
    - minio
