---
- name: Deploy Traefik on docker-srv
  hosts: docker-srv
  become: true

  vars_files:
    - ../group_vars/all/vault.yml
    - ../group_vars/all/services.yml
    - ../group_vars/all/networks.yml
    - ../group_vars/all/volumes.yml
    - ../group_vars/all/domains.yml
    - ../group_vars/all/wp-sevices.yml

  roles:
    - common
    - cloudflared
    - traefik
