---
- hosts: vaultwarden
  vars_files:
    - ../group_vars/all/apps-vault.yml
    - ../group_vars/all/domains.yml
    - ../group_vars/all/services.yml
  tasks:
    - import_role:
        name: vaultwarden
        tasks_from: "admin-{{ admin_action }}"
