---
- name: Configure VyOS router
  hosts: vyos-router
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: vyos.vyos.vyos
    ansible_become: true
    ansible_become_method: sudo
  vars_files:
    - ../group_vars/all/vault.yml
  roles:
    - vyos-router
