---
- name: Deploy WordPress site richweb
  hosts: vm82
  become: true

  vars:
    site_name: "petitsanglais"

  vars_files:
    - ../group_vars/all/vault.yml
    - ../group_vars/all/services.yml
    - ../group_vars/all/networks.yml
    - ../group_vars/all/volumes.yml
    - ../group_vars/all/domains.yml

  roles:
    - wp-restet
#    - docker-volumes
#    - docker-networks
    - wp-sites/petitsanglais

#  tasks:
#    - import_role:
#        name: cloudflared
#        tasks_from: dns-ingress.yml
